import { createHash } from 'node:crypto';
import { z } from 'zod';
import { ensure, OperationsError } from './manifest.mjs';
import { canonicalJson } from './recovery-set.mjs';

export const MONITOR_SIGNALS = Object.freeze(['health','auth','database','storage','email','deals','safety','backup_freshness','monitor_heartbeat']);
const sha=z.string().regex(/^[a-f0-9]{40}$/u), hash=z.string().regex(/^[a-f0-9]{64}$/u), alias=z.string().regex(/^[a-z][a-z0-9-]{0,62}$/u), token=z.string().min(16).max(4096).regex(/^[!-~]+$/u);
const origin=z.string().transform(value=>{try { const u=new URL(value); ensure(u.protocol==='https:'&&u.hostname.endsWith('.workers.dev')&&value===u.origin&&!u.username&&!u.password&&!u.port,'MONITOR_ORIGIN_FORBIDDEN');return u.origin;}catch(error){if(error instanceof OperationsError)throw error;throw new OperationsError('MONITOR_ORIGIN_FORBIDDEN');}});
export const monitorConfigSchema=z.object({workerAlias:alias,origin,environmentAlias:alias,candidateSha:sha,runId:z.uuid(),targetOrigin:origin,targetProbeOrigin:origin.optional(),runtimeEnvironment:z.enum(['development','staging']),maintenanceTarget:z.object({origin,runtimeEnvironment:z.enum(['development','staging']),release:sha}).strict().optional(),configSha256:hash.optional(),webhookSigningSecretSha256:hash,evidenceReadToken:token,watchdogToken:token,backupCheckpointToken:token,maintenanceToken:token,releaseAdoptionToken:token.optional(),targetRole:z.enum(['source','target']).optional(),targetCycleId:z.uuid().optional()}).strict();
const configResponse=z.object({schemaVersion:z.literal(1),environment:alias,release:sha,targetOrigin:origin,runtimeEnvironment:z.enum(['development','staging']),signalFamilies:z.array(z.enum(MONITOR_SIGNALS)).length(9),scheduleMinutes:z.literal(10),configSha256:hash,webhookSigningSecretSha256:hash}).strict();
const signal=z.object({signal:z.enum(MONITOR_SIGNALS),ok:z.boolean(),severity:z.string().max(32),reasonCode:z.string().max(100),checkedAt:z.iso.datetime(),incidentId:z.uuid().optional()}).strict();
const heartbeat=z.object({schemaVersion:z.literal(1),environment:alias,release:sha,observedTargetOrigin:origin.nullable().optional(),lastSuccessfulMonitorCycleAt:z.iso.datetime().nullable(),lastCompletedMonitorCycleAt:z.iso.datetime().nullable(),latestTrustedBackupCheckpointAt:z.iso.datetime().nullable(),latestTrustedBackupDescriptorSha256:hash.nullable(),latestTrustedBackupArtifactSha256:hash.nullable(),integrityFailureEvidenceSha256:hash.nullable(),maintenance:z.object({active:z.boolean(),endsAt:z.iso.datetime(),incidentId:z.uuid().optional(),target:z.object({origin,runtimeEnvironment:z.enum(['development','staging']),release:sha}).strict().nullable().optional()}).nullable()}).strict();
const checkpoint=z.object({schemaVersion:z.literal(1),environment:alias,release:sha,backupRelease:sha,checkpointAt:z.iso.datetime(),descriptorSha256:hash,artifactSha256:hash,integrityFailureEvidenceSha256:hash.nullable(),configSha256:hash}).strict();
const event=z.object({schemaVersion:z.literal(1),incidentId:z.uuid(),signal:z.enum(MONITOR_SIGNALS),state:z.enum(['firing','resolved']),messageId:z.uuid(),eventId:z.string().min(1).max(196),eventType:z.literal('email.delivered'),occurredAt:z.iso.datetime()}).strict();
/** @param {unknown} value */
const digest=value=>createHash('sha256').update(canonicalJson(value)).digest('hex');
/** @param {typeof fetch} fetchImpl @param {string} url @param {string} capability @param {RequestInit} [init] */
async function request(fetchImpl,url,capability,init={}) { try {const response=await fetchImpl(url,{...init,redirect:'manual',signal:AbortSignal.timeout(15_000),headers:{Authorization:`Bearer ${capability}`,...init.headers}});if(!response.ok){await response.body?.cancel().catch(()=>{});throw new OperationsError('MONITOR_READBACK_UNAVAILABLE');}if(response.status===204)return null;const raw=await response.text();ensure(raw.length<=65536,'MONITOR_RESPONSE_LIMIT');return JSON.parse(raw);}catch(error){if(error instanceof OperationsError)throw error;throw new OperationsError('MONITOR_READBACK_UNAVAILABLE');} }
/** Authenticated bounded adapter for the Issue #29 Worker. Provider payloads never leave this module. */
/** @param {unknown} input @param {{fetchImpl?:typeof fetch,now?:()=>string}} [options] */
export function createMonitorAdapter(input,options={}) {const parsed=monitorConfigSchema.safeParse(input);ensure(parsed.success,'MONITOR_CONFIG_INVALID');const c=parsed.data,fetchImpl=options.fetchImpl??fetch,now=options.now??(()=>new Date().toISOString());
  const configuration=()=>({schemaVersion:1,workerAlias:c.workerAlias,origin:c.origin,runId:c.runId,candidateSha:c.candidateSha,environmentAlias:c.environmentAlias,runtimeEnvironment:c.runtimeEnvironment,configSha256:c.configSha256,webhookSigningSecretSha256:c.webhookSigningSecretSha256,targetRole:c.targetRole??'source',targetCycleId:c.targetCycleId??null,targetOrigin:c.targetOrigin,...(c.targetRole==='target'?{targetProbeOrigin:c.targetProbeOrigin}:{}),destinationAlias:'owner-primary',signals:MONITOR_SIGNALS,ruleMappings:MONITOR_SIGNALS.map(signal=>({ruleKey:signal,signal})),evidenceMode:'provider-readback'});
  async function verifiedConfig(){const body=configResponse.safeParse(await request(fetchImpl,c.origin+'/ops/monitor/config',c.evidenceReadToken));ensure(body.success,'MONITOR_CONFIG_RESPONSE_INVALID');const value=body.data;ensure(value.environment===c.environmentAlias&&value.release===c.candidateSha&&value.runtimeEnvironment===c.runtimeEnvironment&&value.targetOrigin===c.targetOrigin&&value.webhookSigningSecretSha256===c.webhookSigningSecretSha256&&(!c.configSha256||c.configSha256===value.configSha256)&&canonicalJson([...value.signalFamilies].sort())===canonicalJson([...MONITOR_SIGNALS].sort()),'MONITOR_CONFIG_IDENTITY_MISMATCH');return {...configuration(),configSha256:value.configSha256,webhookSigningSecretSha256:value.webhookSigningSecretSha256,verifiedAt:now(),status:'verified'};}
  /** @param {string} [expectedRelease] */
  async function state(expectedRelease=c.candidateSha,allowDetachedTarget=false){const raw=await request(fetchImpl,c.origin+'/ops/monitor/state',c.evidenceReadToken),parsed=z.object({...heartbeat.shape,signals:z.array(signal).length(9)}).strict().safeParse(raw);ensure(parsed.success,'MONITOR_STATE_RESPONSE_INVALID');const value=parsed.data;ensure(value.environment===c.environmentAlias&&value.release===expectedRelease&&new Set(value.signals.map(x=>x.signal)).size===9&&canonicalJson([...value.signals.map(x=>x.signal)].sort())===canonicalJson([...MONITOR_SIGNALS].sort()),'MONITOR_STATE_IDENTITY_MISMATCH');if(c.targetRole==='target'&&expectedRelease===c.candidateSha&&!allowDetachedTarget)ensure(c.targetProbeOrigin&&value.maintenance?.active===true&&value.maintenance.target?.origin===c.targetProbeOrigin&&value.observedTargetOrigin===c.targetProbeOrigin,'MONITOR_TARGET_MAINTENANCE_MISMATCH');return value;}
  return {configuration,verifyConfiguration:async()=>{const result=await verifiedConfig();return {...result,evidenceSha256:digest(result)};},
    async readState(){return state();},
    async readSourceGreenState(){ensure((c.targetRole??'source')==='source','MONITOR_SOURCE_STATE_REQUIRED');const value=await state();ensure(value.observedTargetOrigin===c.targetOrigin,'MONITOR_SOURCE_TARGET_UNPROVEN');return value;},
    /** @param {string} ruleKey */ async readSignal(ruleKey){ensure(MONITOR_SIGNALS.includes(ruleKey),'MONITOR_SIGNAL_UNKNOWN');const current=await state(),value=current.signals.find(x=>x.signal===ruleKey);ensure(value,'MONITOR_SIGNAL_UNKNOWN');return {...value,candidateSha:c.candidateSha,configSha256:(await verifiedConfig()).configSha256};},
    async readMonitorHeartbeat(){const raw=heartbeat.safeParse(await request(fetchImpl,c.origin+'/ops/monitor/heartbeat',c.watchdogToken));ensure(raw.success,'MONITOR_HEARTBEAT_RESPONSE_INVALID');const value=raw.data;ensure(value.environment===c.environmentAlias&&value.release===c.candidateSha&&value.lastSuccessfulMonitorCycleAt!==null,'MONITOR_HEARTBEAT_UNPROVEN');return {...value,heartbeatAt:value.lastSuccessfulMonitorCycleAt,checkedAt:now(),candidateSha:c.candidateSha};},
    /** @param {string} incidentId @param {'firing'|'resolved'} state */ async deliveryEvent(incidentId,state){ensure(z.uuid().safeParse(incidentId).success&&['firing','resolved'].includes(state),'MONITOR_INCIDENT_ID_INVALID');const raw=event.safeParse(await request(fetchImpl,c.origin+'/ops/monitor/events?'+new URLSearchParams({incidentId,state}),c.evidenceReadToken));ensure(raw.success&&raw.data.incidentId===incidentId&&raw.data.state===state,'MONITOR_DELIVERY_UNPROVEN');return raw.data;},
    /** @param {unknown} raw */ backupCheckpointOperation(raw){const p=z.object({checkpointAt:z.iso.datetime(),descriptorSha256:hash,artifactSha256:hash,artifactId:z.string().regex(/^[1-9][0-9]{0,17}$/u).optional()}).strict().safeParse(raw);ensure(p.success,'MONITOR_BACKUP_CHECKPOINT_INVALID');let inspected=false;return {inspect:async()=>{await verifiedConfig();inspected=true;return {status:'verified',evidenceSha256:digest(p.data)};},mutate:async()=>{ensure(inspected,'MONITOR_PRE_MUTATION_INSPECTION_REQUIRED');try {await request(fetchImpl,c.origin+'/ops/monitor/backup-checkpoint',c.backupCheckpointToken,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schemaVersion:1,environment:c.environmentAlias,release:c.candidateSha,checkpointAt:p.data.checkpointAt,descriptorSha256:p.data.descriptorSha256,artifactSha256:p.data.artifactSha256})});}catch{throw new OperationsError('MONITOR_MUTATION_UNCERTAIN_READBACK_ONLY');}},readback:async()=>{const current=await state(),record=checkpoint.safeParse(await request(fetchImpl,c.origin+'/ops/monitor/backup-checkpoint',c.evidenceReadToken));ensure(record.success,'MONITOR_BACKUP_CHECKPOINT_RESPONSE_INVALID');const configuration=await verifiedConfig(),value=record.data;ensure(current.integrityFailureEvidenceSha256===null&&current.latestTrustedBackupCheckpointAt===p.data.checkpointAt&&current.latestTrustedBackupDescriptorSha256===p.data.descriptorSha256&&current.latestTrustedBackupArtifactSha256===p.data.artifactSha256&&value.environment===c.environmentAlias&&value.release===c.candidateSha&&value.backupRelease===c.candidateSha&&value.checkpointAt===p.data.checkpointAt&&value.descriptorSha256===p.data.descriptorSha256&&value.artifactSha256===p.data.artifactSha256&&value.integrityFailureEvidenceSha256===null&&value.configSha256===configuration.configSha256,'MONITOR_BACKUP_CHECKPOINT_READBACK_MISMATCH');return {status:'verified',...p.data,candidateSha:c.candidateSha,configSha256:configuration.configSha256,verifiedAt:now(),evidenceSha256:digest(p.data)};}};},
    /** @param {unknown} raw */ releaseAdoptionOperation(raw){const p=z.object({environment:alias,previousRelease:sha,release:sha,previousConfigSha256:hash,protectedMergeEvidenceSha256:hash}).strict().safeParse(raw);ensure(p.success&&p.data.environment===c.environmentAlias&&p.data.release===c.candidateSha&&p.data.previousRelease!==c.candidateSha,'MONITOR_RELEASE_ADOPTION_INVALID');const releaseAdoptionToken=c.releaseAdoptionToken;if(typeof releaseAdoptionToken!=='string')throw new OperationsError('MONITOR_RELEASE_ADOPTION_TOKEN_REQUIRED');let inspected=false;return {inspect:async()=>{const before=await state(p.data.previousRelease);inspected=true;return {status:'verified',environment:before.environment,previousRelease:before.release,previousConfigSha256:p.data.previousConfigSha256,evidenceSha256:digest({environment:before.environment,previousRelease:before.release,previousConfigSha256:p.data.previousConfigSha256})};},mutate:async()=>{ensure(inspected,'MONITOR_PRE_MUTATION_INSPECTION_REQUIRED');try{const result=z.object({schemaVersion:z.literal(1),candidateSha:sha,previousCandidateSha:sha,previousConfigSha256:hash}).strict().safeParse(await request(fetchImpl,c.origin+'/ops/monitor/release-update',releaseAdoptionToken,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schemaVersion:1,...p.data})}));ensure(result.success&&result.data.candidateSha===p.data.release&&result.data.previousCandidateSha===p.data.previousRelease&&result.data.previousConfigSha256===p.data.previousConfigSha256,'MONITOR_RELEASE_ADOPTION_SUBMISSION_INVALID');return {status:'submitted',...result.data};}catch{throw new OperationsError('MONITOR_RELEASE_MUTATION_UNCERTAIN_READBACK_ONLY');}},readback:async()=>{const current=await state(p.data.release),configuration=await verifiedConfig();return {status:'verified',...p.data,candidateSha:current.release,configSha256:configuration.configSha256,verifiedAt:now(),evidenceSha256:digest({environment:p.data.environment,previousRelease:p.data.previousRelease,release:current.release,previousConfigSha256:p.data.previousConfigSha256,protectedMergeEvidenceSha256:p.data.protectedMergeEvidenceSha256,configSha256:configuration.configSha256})};}};},
    /** @param {unknown} raw */ maintenanceOperation(raw){const target=z.object({origin,readinessUrl:z.string().url(),readinessToken:token,runtimeEnvironment:z.enum(['development','staging']),release:sha}).strict();const p=z.discriminatedUnion('action',[z.object({action:z.literal('start'),startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),incidentId:z.uuid()}).strict(),z.object({action:z.literal('attach-target'),incidentId:z.uuid(),target}).strict(),z.object({action:z.literal('remove-target'),incidentId:z.uuid()}).strict(),z.object({action:z.literal('end'),incidentId:z.uuid()}).strict()]).safeParse(raw);ensure(p.success,'MONITOR_MAINTENANCE_INVALID');let inspected=false;return {inspect:async()=>{await verifiedConfig();inspected=true;return {status:'verified',evidenceSha256:digest(p.data)};},mutate:async()=>{ensure(inspected,'MONITOR_PRE_MUTATION_INSPECTION_REQUIRED');try{let path='/ops/monitor/maintenance',method='PUT';
      /** @type {Record<string,unknown>} */
      let body={schemaVersion:1,incidentId:p.data.incidentId};if(p.data.action==='start')body={schemaVersion:1,startsAt:p.data.startsAt,endsAt:p.data.endsAt,incidentId:p.data.incidentId};if(p.data.action==='attach-target'){path+='/target';body={schemaVersion:1,incidentId:p.data.incidentId,target:p.data.target};}if(p.data.action==='remove-target'){path+='/target';method='DELETE';}if(p.data.action==='end')method='DELETE';await request(fetchImpl,c.origin+path,c.maintenanceToken,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch{throw new OperationsError('MONITOR_MUTATION_UNCERTAIN_READBACK_ONLY');}},readback:async()=>{const current=await state(c.candidateSha,p.data.action==='remove-target'),maint=current.maintenance;if(p.data.action==='start')ensure(maint?.active===true&&maint.endsAt===p.data.endsAt&&maint.incidentId===p.data.incidentId&&!maint.target,'MONITOR_MAINTENANCE_READBACK_MISMATCH');if(p.data.action==='attach-target')ensure(maint?.active===true&&maint.incidentId===p.data.incidentId&&maint.target?.origin===p.data.target.origin&&maint.target.runtimeEnvironment===p.data.target.runtimeEnvironment&&maint.target.release===p.data.target.release,'MONITOR_MAINTENANCE_READBACK_MISMATCH');if(p.data.action==='remove-target')ensure(maint?.active===true&&maint.incidentId===p.data.incidentId&&!maint.target,'MONITOR_MAINTENANCE_READBACK_MISMATCH');if(p.data.action==='end')ensure(maint===null,'MONITOR_MAINTENANCE_READBACK_MISMATCH');const safe=p.data.action==='attach-target'?{...p.data,target:{origin:p.data.target.origin,runtimeEnvironment:p.data.target.runtimeEnvironment,release:p.data.target.release}}:p.data;return {status:'verified',...safe,resourceId:p.data.incidentId,readBackAt:now(),evidenceSha256:digest(safe)};}};}
  };}
