import { createHash } from 'node:crypto';
import { z } from 'zod';
import { ensure } from './manifest.mjs';
import { canonicalJson } from './recovery-set.mjs';

/** @typedef {ReturnType<import('./monitor-adapter.mjs').createMonitorAdapter>} MonitorAdapter */
/** @param {unknown} value */
const digest=value=>createHash('sha256').update(canonicalJson(value)).digest('hex');
const sha=z.string().regex(/^[a-f0-9]{64}$/u);
const phaseSchema=z.object({schemaVersion:z.literal(1),evidenceMode:z.literal('provider-readback'),runId:z.uuid(),candidateSha:z.string().regex(/^[a-f0-9]{40}$/u),configSha256:sha,ruleKey:z.string(),phase:z.enum(['failure','recovery']),windowStart:z.iso.datetime(),observedAt:z.iso.datetime(),signal:z.object({signal:z.string(),ok:z.boolean(),severity:z.string(),reasonCode:z.string(),checkedAt:z.iso.datetime(),incidentId:z.uuid().optional(),candidateSha:z.string().regex(/^[a-f0-9]{40}$/u),configSha256:sha}).strict(),event:z.object({schemaVersion:z.literal(1),incidentId:z.uuid(),signal:z.string(),state:z.enum(['firing','resolved']),messageId:z.uuid(),eventId:z.string(),eventType:z.literal('email.delivered'),occurredAt:z.iso.datetime()}).strict(),evidenceSha256:sha}).strict();

/** Read one authenticated Worker signal and its exact correlated Resend delivered-event proof. */
/** @param {MonitorAdapter} adapter @param {{ruleKey:string,phase:'failure'|'recovery',windowStart:string,incidentId?:string,now?:string}} input */
export async function captureMonitoringPhase(adapter,input) {const config=adapter.configuration(),now=input.now??new Date().toISOString();ensure(['failure','recovery'].includes(input.phase)&&Date.parse(input.windowStart)<=Date.parse(now)&&Date.parse(now)-Date.parse(input.windowStart)<=7_200_000,'MONITORING_PROOF_WINDOW_INVALID');ensure(config.signals.includes(input.ruleKey),'MONITORING_RULE_UNKNOWN');const verified=await adapter.verifyConfiguration(),observed=await adapter.readSignal(input.ruleKey);const incidentId=input.incidentId??observed.incidentId;ensure(z.uuid().safeParse(incidentId).success,'MONITORING_INCIDENT_ID_REQUIRED');ensure(input.phase==='failure'?observed.ok===false:observed.ok===true,'MONITORING_PHASE_NOT_OBSERVED');ensure(observed.incidentId===incidentId&&observed.candidateSha===config.candidateSha&&observed.configSha256===verified.configSha256&&Date.parse(observed.checkedAt)>=Date.parse(input.windowStart)&&Date.parse(observed.checkedAt)<=Date.parse(now),'MONITORING_EVALUATION_IDENTITY_OR_TIME_INVALID');const state=input.phase==='failure'?'firing':'resolved',event=await adapter.deliveryEvent(/** @type {string} */ (incidentId),state);ensure(event.incidentId===incidentId&&event.eventType==='email.delivered'&&event.signal===input.ruleKey&&event.state===state&&Date.parse(event.occurredAt)>=Date.parse(input.windowStart)&&Date.parse(event.occurredAt)<=Date.parse(now),'MONITORING_DELIVERY_NOT_PROVEN');const body={schemaVersion:1,evidenceMode:'provider-readback',runId:config.runId,candidateSha:config.candidateSha,configSha256:verified.configSha256,ruleKey:input.ruleKey,phase:input.phase,windowStart:input.windowStart,observedAt:now,signal:observed,event};return {...body,evidenceSha256:digest(body)};}

/** Explicit owner acknowledgement remains a runbook action; an automated delivery event never proves a human read. */
/** @param {MonitorAdapter} adapter @param {{ruleKey:string,phases:unknown[],acknowledgements:{ruleKey:string,failureEventId:string,acknowledgedAt:string,roleAlias:'owner'|'authorized-operator',inboxEvidenceSha256:string}[],now?:string}} input */
export async function verifyMonitoringRuleJourney(adapter,input) {const p=adapter.configuration(),key=input.ruleKey,now=input.now??new Date().toISOString(),matched=input.phases.filter(/** @param {unknown} value */value=>typeof value==='object'&&value!==null&&/** @type {{ruleKey?:unknown}} */(value).ruleKey===key);ensure(p.signals.includes(key)&&matched.length===2,'MONITORING_RULE_COVERAGE_INCOMPLETE');const verified=await adapter.verifyConfiguration();const parsed=[];for(const raw of matched){const result=phaseSchema.safeParse(raw);ensure(result.success,'MONITORING_PHASE_INVALID');const {evidenceSha256,...body}=result.data;ensure(digest(body)===evidenceSha256&&body.runId===p.runId&&body.candidateSha===p.candidateSha&&Date.parse(now)>=Date.parse(body.observedAt)&&Date.parse(now)-Date.parse(body.observedAt)<=7_200_000,'MONITORING_PHASE_IDENTITY_OR_HASH_MISMATCH');ensure(body.configSha256===verified.configSha256&&body.signal.configSha256===verified.configSha256&&body.signal.candidateSha===p.candidateSha&&body.signal.incidentId===body.event.incidentId&&body.signal.signal===key&&body.event.signal===key&&body.event.eventType==='email.delivered'&&body.event.state===(body.phase==='failure'?'firing':'resolved')&&Date.parse(body.signal.checkedAt)>=Date.parse(body.windowStart)&&Date.parse(body.event.occurredAt)>=Date.parse(body.windowStart)&&Date.parse(body.windowStart)<=Date.parse(body.observedAt)&&Date.parse(body.observedAt)-Date.parse(body.windowStart)<=7_200_000&&Date.parse(body.signal.checkedAt)<=Date.parse(body.observedAt)&&Date.parse(body.event.occurredAt)<=Date.parse(body.observedAt),'MONITORING_NESTED_IDENTITY_MISMATCH');const readback=await adapter.deliveryEvent(body.event.incidentId,body.event.state);ensure(canonicalJson(readback)===canonicalJson(body.event),'MONITORING_EVENT_READBACK_MISMATCH');parsed.push(body);}
  const failure=parsed.find(x=>x.phase==='failure'),recovery=parsed.find(x=>x.phase==='recovery');ensure(failure&&recovery&&failure.signal.ok===false&&recovery.signal.ok===true&&failure.event.incidentId===recovery.event.incidentId&&failure.event.messageId!==recovery.event.messageId&&failure.event.eventId!==recovery.event.eventId&&Date.parse(recovery.signal.checkedAt)>Date.parse(failure.signal.checkedAt)&&Date.parse(recovery.event.occurredAt)>Date.parse(failure.event.occurredAt),'MONITORING_RECOVERY_SEQUENCE_INVALID');const acknowledgements=input.acknowledgements.filter(x=>x.ruleKey===key);ensure(acknowledgements.length===1,'MONITORING_ACKNOWLEDGEMENT_MISSING');const ack=acknowledgements[0],elapsed=Date.parse(ack.acknowledgedAt)-Date.parse(failure.event.occurredAt);ensure(ack.failureEventId===failure.event.eventId&&['owner','authorized-operator'].includes(ack.roleAlias)&&sha.safeParse(ack.inboxEvidenceSha256).success&&elapsed>=0&&elapsed<=900_000&&Date.parse(ack.acknowledgedAt)<=Date.parse(recovery.event.occurredAt),'MONITORING_ACKNOWLEDGEMENT_INVALID');return {ruleKey:key,destinationAlias:'owner-primary',incidentId:failure.event.incidentId,firedAt:failure.signal.checkedAt,deliveredAt:failure.event.occurredAt,acknowledgedAt:ack.acknowledgedAt,recoveryEvaluatedAt:recovery.signal.checkedAt,recoveryDeliveredAt:recovery.event.occurredAt,failureEventId:failure.event.eventId,recoveryEventId:recovery.event.eventId,ackEvidenceSha256:ack.inboxEvidenceSha256};}

/** @param {MonitorAdapter} adapter @param {{phases:unknown[],acknowledgements:{ruleKey:string,failureEventId:string,acknowledgedAt:string,roleAlias:'owner'|'authorized-operator',inboxEvidenceSha256:string}[],now?:string}} input */
export async function verifyMonitoringProof(adapter,input) {const p=adapter.configuration(),now=input.now??new Date().toISOString();ensure(input.phases.length===p.signals.length*2&&input.acknowledgements.length===p.signals.length,'MONITORING_RULE_COVERAGE_INCOMPLETE');const configuration=await adapter.verifyConfiguration(),timelines=[];for(const key of p.signals)timelines.push(await verifyMonitoringRuleJourney(adapter,{...input,ruleKey:key,now}));const body={schemaVersion:1,status:'verified',evidenceMode:'provider-readback',candidateSha:p.candidateSha,configSha256:configuration.configSha256,runId:p.runId,environmentAlias:p.environmentAlias,destinationAlias:'owner-primary',verifiedAt:now,configurationEvidenceSha256:configuration.evidenceSha256,configuration,sourceConfigSha256:configuration.configSha256,signalFamilies:p.signals,ruleMappings:p.ruleMappings,timelines};return {...body,evidenceSha256:digest(body)};}
