import { expect, it } from 'vitest';
import { createIssue29Monitor, type MonitorEnv } from '../../workers/issue29-monitor/src/index';

const sha='a'.repeat(40), now=Date.parse('2026-09-08T12:00:00.000Z'), names=['health','auth','database','storage','email','deals','safety','backup_freshness','monitor_heartbeat'];
const token=(value:string)=>value.repeat(43);
class Store { values=new Map<string,string>(); async get(key:string){return this.values.get(key)??null;} async put(key:string,value:string){this.values.set(key,value);} }
function config(state=new Store()):MonitorEnv{return {MONITOR_STATE:state,TARGET_ORIGIN:'https://source.example.test',PUBLIC_HEALTH_URL:'https://source.example.test/',READINESS_URL:'https://source.example.test/api/operations/readiness',READINESS_TOKEN:token('r'),EXPECTED_ENVIRONMENT:'synthetic-recovery',RUNTIME_ENVIRONMENT:'development',EXPECTED_RELEASE_SHA:sha,RESEND_API_KEY:'re_1234567890',RESEND_FROM:'monitor@example.test',RESEND_TO:'owner@example.test',RESEND_WEBHOOK_SECRET:'whsec_dGVzdF9zaWduaW5nX2tleV9mb3JfaXNzdWUyOQ==',BACKUP_CHECKPOINT_TOKEN:token('b'),WATCHDOG_TOKEN:token('w'),EVIDENCE_READ_TOKEN:token('e'),MAINTENANCE_TOKEN:token('m'),RELEASE_ADOPTION_TOKEN:token('u')};}
function response(environment='development'){return Response.json({schemaVersion:1,signals:names.map((signal,index)=>({signal,environment,deploymentIdentity:sha,checkedAt:new Date(now).toISOString(),ok:true,severity:'none',reasonCode:'healthy',correlationId:`11111111-1111-4111-8111-${String(index).padStart(12,'0')}`,runbookAnchor:`docs/INCIDENT-RESPONSE.md#${signal.replaceAll('_','-')}`}))});}

it('keeps source backup/heartbeat state through a target maintenance attachment and requires exact incident removal',async()=>{
 const state=new Store(),env=config(state),seen:string[]=[];const monitor=createIssue29Monitor({now:()=>now,fetch:async input=>{const u=new URL(String(input));seen.push(u.origin);if(u.pathname==='/')return new Response(null,{status:200,headers:{'x-deployed-git-sha':sha}});return response(u.origin==='https://restore.example.test'?'development':'development');}});
 const checkpoint={schemaVersion:1,environment:'synthetic-recovery',release:sha,checkpointAt:new Date(now).toISOString(),descriptorSha256:'d'.repeat(64),artifactSha256:'c'.repeat(64)};
 expect((await monitor.fetch(new Request('https://monitor/ops/monitor/backup-checkpoint',{method:'POST',headers:{authorization:`Bearer ${env.BACKUP_CHECKPOINT_TOKEN}`,'content-type':'application/json'},body:JSON.stringify(checkpoint)}),env)).status).toBe(204);
 const incident='22222222-2222-4222-8222-222222222222';expect((await monitor.fetch(new Request('https://monitor/ops/monitor/maintenance',{method:'PUT',headers:{authorization:`Bearer ${env.MAINTENANCE_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({schemaVersion:1,startsAt:new Date(now-1000).toISOString(),endsAt:new Date(now+60000).toISOString(),incidentId:incident})}),env)).status).toBe(204);
 expect((await monitor.fetch(new Request('https://monitor/ops/monitor/maintenance/target',{method:'PUT',headers:{authorization:`Bearer ${env.MAINTENANCE_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({schemaVersion:1,incidentId:'33333333-3333-4333-8333-333333333333',target:{origin:'https://restore.example.test',readinessUrl:'https://restore.example.test/api/operations/readiness',readinessToken:token('t'),runtimeEnvironment:'development',release:sha}})}),env)).status).toBe(409);
 expect((await monitor.fetch(new Request('https://monitor/ops/monitor/maintenance/target',{method:'PUT',headers:{authorization:`Bearer ${env.MAINTENANCE_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({schemaVersion:1,incidentId:incident,target:{origin:'https://restore.example.test',readinessUrl:'https://restore.example.test/api/operations/readiness',readinessToken:token('t'),runtimeEnvironment:'development',release:sha}})}),env)).status).toBe(204);
 await monitor.scheduled(env);expect(seen).toContain('https://restore.example.test');const heartbeat=await monitor.fetch(new Request('https://monitor/ops/monitor/heartbeat',{headers:{authorization:`Bearer ${env.WATCHDOG_TOKEN}`}}),env);expect(await heartbeat.json()).toMatchObject({latestTrustedBackupCheckpointAt:checkpoint.checkpointAt,maintenance:{target:{origin:'https://restore.example.test'}}});
 expect((await monitor.fetch(new Request('https://monitor/ops/monitor/maintenance/target',{method:'DELETE',headers:{authorization:`Bearer ${env.MAINTENANCE_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({schemaVersion:1,incidentId:incident})}),env)).status).toBe(204);await monitor.scheduled(env);expect(seen).toContain('https://source.example.test');
});
