import { describe, expect, it } from 'vitest';
import { chmod, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { executeDailyCanary, executeMonitoringAction, monitoringExecutionSettingsSchema } from '../../scripts/issue29-operations/monitoring-execution.mjs';
import { manifestFixture } from '../fixtures/issue29-operations';
import { monitorConfig, monitorReadback } from '../fixtures/issue29-monitor';
import { MONITOR_SIGNALS } from '../../scripts/issue29-operations/monitor-adapter.mjs';
import { writePrivateManifest } from '../../scripts/issue29-operations/manifest.mjs';

const now='2026-09-05T12:00:00.000Z';
describe('Issue 29 monitor execution',()=>{
  it('rejects an unrecognized private action before any provider mutation',async()=>{
    expect(monitoringExecutionSettingsSchema.safeParse({schemaVersion:1,operation:'incident-drill',action:'delete-production',monitor:{}}).success).toBe(false);
    await expect(executeMonitoringAction({manifestPath:'/tmp/nonexistent',repositoryRoot:process.cwd(),candidate:{sha:'a'.repeat(40),tree:'b'.repeat(40),deploymentId:'v'},settings:{schemaVersion:1,operation:'incident-drill',action:'delete-production'}})).rejects.toThrow('MONITORING_SETTINGS_INVALID');
  });
  it('requires private Resend webhook binding material only for monitor configuration',()=>{const m=manifestFixture(),binding={providerToken:'private-provider-token',source:{apiUrl:m.source!.url,serviceKey:'private-service-role-key'},deployment:{accountId:'c'.repeat(32),workerName:`issue29-${m.runId}`,versionId:m.candidate.deploymentId,origin:`https://issue29-${m.runId}.owner.workers.dev`,readToken:'private-cloudflare-token'}},base={schemaVersion:1 as const,operation:'configure-monitoring' as const,action:'configure' as const,actionId:'configure',monitor:{...monitorConfig,runId:m.runId,candidateSha:m.candidate.sha,targetOrigin:binding.deployment.origin},binding};expect(monitoringExecutionSettingsSchema.safeParse(base).success).toBe(false);expect(monitoringExecutionSettingsSchema.safeParse({...base,resendWebhook:{id:'56565656-5656-4565-8565-565656565656',apiKey:'re_privatewebhookkey123456',signingSecret:'whsec_abcdefghijklmnopqrstuv'}}).success).toBe(true);});

  it('runs a daily Free-only synthetic canary once, polls signed delivered readback, and records a separate checkpoint',async()=>{
    const directory=await mkdtemp(join(tmpdir(),'i29-daily-canary-'));await chmod(directory,0o700);
    try {const manifestPath=join(directory,'manifest.json'),repositoryRoot=process.cwd(),m=manifestFixture();m.target=null;m.state='monitoring_configured';m.cleanup.resources.push({provider:'supabase',id:m.source!.ref,runId:m.runId,createdAt:now,evidenceSha256:'e'.repeat(64),disposition:'persistent',absentAt:null});
      const binding={providerToken:'private-provider-token',source:{apiUrl:m.source!.url,serviceKey:'private-service-role-key'},deployment:{accountId:'c'.repeat(32),workerName:`issue29-${m.runId}`,versionId:m.candidate.deploymentId,origin:`https://issue29-${m.runId}.owner.workers.dev`,readToken:'private-cloudflare-token'}};
      const config={...monitorConfig,runId:m.runId,candidateSha:m.candidate.sha,targetOrigin:binding.deployment.origin};const monitor=monitorReadback(config,now);m.monitoring={workerAlias:config.workerAlias,destinationAlias:'owner-primary',ruleAliases:[...MONITOR_SIGNALS],configSha256:monitor.config.configSha256};await writePrivateManifest(manifestPath,m,{repositoryRoot,now});
      const executionId='45454545-4545-4454-8454-454545454545',messageId='56565656-5656-4565-8565-565656565656';let current=now,sends=0,checkpoints=0,sleeps=0;let email:Record<string,unknown>={},checkpoint:Record<string,unknown>={};
      const fetchImpl:typeof fetch=async(url,init)=>{const u=new URL(String(url));if(u.origin===config.origin){if(u.pathname==='/ops/monitor/config')return Response.json(monitor.config);if(u.pathname==='/ops/monitor/state')return Response.json(monitor.state);if(u.pathname==='/ops/monitor/heartbeat'){const {signals,...heartbeat}=monitor.state;return Response.json(heartbeat);}throw new Error('unexpected monitor route');}
        if(u.hostname==='api.supabase.com'){if(u.pathname.includes('/organizations/'))return Response.json({id:'owned-org',plan:'free'});if(u.pathname.endsWith('/api-keys'))return Response.json([{name:'service_role',api_key:binding.source.serviceKey}]);return Response.json({ref:m.source!.ref,organization_slug:'owned-org',region:'eu-central-1',status:'ACTIVE_HEALTHY',database:{version:'17.6.1'}});}
        if(u.hostname==='api.cloudflare.com'){if(u.pathname.endsWith('/deployments'))return Response.json({success:true,result:{deployments:[{versions:[{version_id:m.candidate.deploymentId,percentage:100}]}]}});return Response.json({success:true,result:{id:m.candidate.deploymentId,metadata:{created_on:now},resources:{bindings:[['RELEASE_COMMIT_SHA',m.candidate.sha],['PUBLIC_SUPABASE_URL',m.source!.url],['APP_ENV','development'],['ISSUE29_CANDIDATE_TREE',m.candidate.tree],['ISSUE29_RUN_ID',m.runId]].map(([name,text])=>({name,text,type:'plain_text'}))}}});}
        if(u.hostname.endsWith('.workers.dev'))return new Response(null,{status:200,headers:{'x-deployed-git-sha':m.candidate.sha}});
        if(u.hostname==='api.resend.com'){const headers={'x-resend-daily-quota':'1','x-resend-monthly-quota':'20'};if(u.pathname.startsWith('/domains/'))return Response.json({id:'67676767-6767-4676-8676-676767676767',name:'example.test',status:'verified',capabilities:{sending:'enabled'}},{headers});if(u.pathname.startsWith('/webhooks/'))return Response.json({id:'78787878-7878-4787-8787-787878787878',endpoint:binding.deployment.origin+'/api/webhooks/resend',status:'enabled',events:['email.delivered']},{headers});if(u.pathname==='/emails'){const pending=JSON.parse(await readFile(manifestPath,'utf8')).pending;expect(pending.resourceId).toContain('canary-send');sends++;email=JSON.parse(String(init?.body));return Response.json({id:messageId});}return Response.json({id:messageId,...email,created_at:now,last_event:sleeps?'delivered':'sent'});}
        if(u.pathname.endsWith('/record_operations_checkpoint')){const pending=JSON.parse(await readFile(manifestPath,'utf8')).pending;expect(pending.resourceId).toContain('canary-checkpoint');checkpoints++;const body=JSON.parse(String(init?.body));checkpoint={deploymentIdentity:body.p_deployment_identity,checkpointAt:body.p_checkpoint_at,ok:body.p_ok,evidenceSha256:body.p_evidence_sha256};return Response.json(null);}if(u.pathname.endsWith('/get_operations_snapshot'))return Response.json({checkpoints:{email_canary:checkpoint}});throw new Error('Unexpected fixture path');};
      const canary={database:{scope:{mode:'hosted' as const,role:'source' as const,runId:m.runId,projectRef:m.source!.ref,sourceRef:m.source!.ref,preservedRefs:m.preservedRefs,createdResourceEvidenceSha256:'e'.repeat(64),apiUrl:m.source!.url},connection:{host:`db.${m.source!.ref}.supabase.co`,port:5432,user:'postgres',database:'postgres',password:'private-db-secret-123',sslmode:'verify-full' as const},toolchain:{mode:'container' as const}},resend:{apiKey:'re_privatecanarykey123456789',domainId:'67676767-6767-4676-8676-676767676767',webhookId:'78787878-7878-4787-8787-787878787878',from:'canary@example.test',to:'private-canary@example.test',operationId:m.runId,windowStart:now,webhookOrigin:binding.deployment.origin,syntheticScopeEvidenceSha256:'a'.repeat(64),freePlanEvidence:{observedAt:'2026-01-01T00:00:00.000Z',remainingDaily:1,quotedCost:0 as const,evidenceSha256:'b'.repeat(64)}}};
      const settings={schemaVersion:1 as const,operation:'monitoring-proof' as const,action:'canary-send' as const,actionId:'daily',monitor:config,binding,canary};const options={manifestPath,repositoryRoot,candidate:m.candidate,settings,executionId,preparedAt:now,fetchImpl,clock:()=>current,ledgerReader:async()=>sleeps?[{providerEventId:'msg_dailycanaryevent123',providerMessageId:messageId,eventType:'email.delivered',occurredAt:current,receivedAt:current}]:[],sleep:async(milliseconds:number)=>{expect(milliseconds).toBe(30000);sleeps++;current='2026-09-05T12:00:30.000Z';}};
      const proof=await executeDailyCanary(options);expect(proof).toMatchObject({kind:'daily-synthetic-canary',checkpointAt:'2026-09-05T12:00:30.000Z'});expect(sends).toBe(1);expect(checkpoints).toBe(1);expect(sleeps).toBe(1);await executeDailyCanary(options);expect(sends).toBe(1);expect(checkpoints).toBe(1);expect(JSON.stringify(proof)).not.toMatch(/private-|example.test/);
    } finally {await rm(directory,{recursive:true,force:true});}
  });
});
