import {afterEach,expect,it,vi} from 'vitest';
import {mkdtemp,writeFile,rm,readFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {executeIsolationVerification} from '../../scripts/issue29-operations/hosted-execution.mjs';
import {canonicalJson} from '../../scripts/issue29-operations/recovery-set.mjs';
import {readPrivateManifest,writePrivateManifest} from '../../scripts/issue29-operations/manifest.mjs';
import {manifestFixture,maintenanceFixture} from '../fixtures/issue29-operations';
const now='2026-09-05T12:01:00.000Z',dirs:string[]=[];
const hash=(v:unknown)=>createHash('sha256').update(canonicalJson(v)).digest('hex');
afterEach(async()=>{for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
async function fixture(){
 const d=await mkdtemp(join(tmpdir(),'issue29-isolation-'));dirs.push(d);const m=manifestFixture();m.state='integrity_verified';m.preservedRefs=['nuhkpqjjyuygiemrxbdp'];m.forbiddenRefs=[m.source!.ref,...m.preservedRefs];m.maintenance=maintenanceFixture(m,now);m.targetDeploymentId='target-version';
 for(const [project,disposition]of [[m.source,'persistent'],[m.target,'disposable']] as const){const creation={schemaVersion:1,kind:'issue29-supabase-created',runId:m.runId,project,empty:true};await writeFile(join(d,hash(creation)+'.json'),canonicalJson(creation),{mode:0o600});m.cleanup.resources.push({provider:'supabase',id:project!.ref,runId:m.runId,createdAt:now,evidenceSha256:hash(creation),disposition,absentAt:null});}
 const q={provider:{runId:m.runId,projectRef:m.target!.ref,targetWorkerResourcesAbsent:true,customSmtp:false,edgeFunctionCount:0,enabledAuthHookCount:0},baselineSha256:'b'.repeat(64)};await writeFile(join(d,hash(q)+'.json'),canonicalJson(q),{mode:0o600});m.history.push({step:'quarantine',operationId:m.runId,resourceId:m.target!.ref,completedAt:now,evidenceSha256:hash(q)});
 const manifestPath=join(d,'manifest.json'),settingsPath=join(d,'settings.json');await writePrivateManifest(manifestPath,m,{repositoryRoot:process.cwd(),now});
 const settings={schemaVersion:1,operation:'verify-isolation',providerToken:'private-provider-token',capabilityId:m.capabilityIds['source-read'],twoSlotAuthorization:{schemaVersion:1,policy:'supabase-free-two-active-projects',organizationId:m.source!.organizationId,preservedStagingRef:m.preservedRefs[0],authorizedAt:now,expiresAt:'2026-09-05T13:00:00.000Z',maximumActiveProjects:2,maximumCost:0,evidenceSha256:'a'.repeat(64)},sourcePrivateDirectory:d,sourceWorker:{settings:{purpose:'source'},privateDirectory:join(d,'source'),readToken:'private-read-token'},targetWorker:{settings:{purpose:'target'},privateDirectory:join(d,'target'),readToken:'private-read-token'},targetBinding:{source:{apiUrl:m.target!.url,serviceKey:'target-secret-'.repeat(4)}},preserved:{canonicalStagingRef:m.preservedRefs[0],productionRefs:[],historicalRefs:[]}};
 for(const role of ['source','target']){await mkdir(join(d,role),{mode:0o700});await writeFile(join(d,role,`worker-${role}.secrets.json`),JSON.stringify({SUPABASE_SECRET_KEY:`${role}-secret-`.repeat(4),OPERATIONS_MONITOR_TOKEN:`${role}-monitor-`.repeat(4)}),{mode:0o600});}
 await writeFile(settingsPath,JSON.stringify(settings),{mode:0o600});
 const preflightEvidence={kind:'issue29-supabase-preflight',providerInventory:{projects:[{ref:m.preservedRefs[0],status:'ACTIVE_HEALTHY'},{ref:m.source!.ref,status:'INACTIVE'},{ref:m.target!.ref,status:'ACTIVE_HEALTHY'}]}};
 const pausedEvidence={projectRef:m.source!.ref,status:'INACTIVE',checkedAt:now};
 const adapterFactory=vi.fn(()=>({preflight:async()=>({plan:'free',quotedCost:0,projectLimit:2,activeProjectCount:2,availableProjects:0,inventoryRefs:[...m.preservedRefs,m.source!.ref,m.target!.ref].sort(),evidence:preflightEvidence,evidenceSha256:hash(preflightEvidence)}),readPaused:async()=>({project:m.source,status:'INACTIVE',evidence:pausedEvidence,evidenceSha256:hash(pausedEvidence)})}));
 const workerBinding=vi.fn(async({settings:s}:any)=>({purpose:s.purpose,projectRef:s.purpose==='source'?m.source!.ref:m.target!.ref,accountId:'a'.repeat(32),origin:`https://${s.purpose}.fixture.workers.dev`}));
 return{d,m,settings,manifestPath,settingsPath,repositoryRoot:process.cwd(),candidate:m.candidate,operation:'verify-isolation',now,dependencies:{adapterFactory,workerBinding,targetBinding:async()=>({targetRef:m.target!.ref}),seedEvidence:async()=>({summary:{inventorySha256:m.sourceProvenance!.inventorySha256}})}};
}
it('generates hash-bound isolation only from exact preserved inventory and independent environment readbacks',async()=>{const f=await fixture();const result=await executeIsolationVerification(f,f.dependencies as any);const m=await readPrivateManifest(f.manifestPath,f);expect(m.pending).toBeNull();expect(m.state).toBe('integrity_verified');const proof=JSON.parse(await readFile(join(f.d,result.evidenceSha256+'.json'),'utf8'));expect(proof.evidenceMode).toBe('deterministic-http-fixture');expect(proof.sourceRef).not.toBe(proof.targetRef);expect(proof.preserved.canonicalStagingRef).toBe('nuhkpqjjyuygiemrxbdp');expect(proof.noSharedCredentialsVerified).toBe(true);expect(JSON.stringify(proof)).not.toContain('private-provider-token');});
it.each(['unknown-preserved','shared-service-key','wrong-target-key','source-target-collision','quarantine-missing'])('rejects %s rather than asserting isolation PASS',async fault=>{const f=await fixture();if(fault==='unknown-preserved')f.settings.preserved.historicalRefs.push('cdefghijklmnopqrstuv' as never);if(fault==='shared-service-key')await writeFile(join(f.d,'target','worker-target.secrets.json'),JSON.stringify({SUPABASE_SECRET_KEY:'source-secret-'.repeat(4),OPERATIONS_MONITOR_TOKEN:'target-monitor-'.repeat(4)}));if(fault==='wrong-target-key')f.settings.targetBinding.source.serviceKey='wrong-private-key';if(fault==='source-target-collision')f.m.target=f.m.source;if(fault==='quarantine-missing')f.m.history=[];await writeFile(f.settingsPath,JSON.stringify(f.settings));if(fault==='source-target-collision')await writeFile(f.manifestPath,JSON.stringify(f.m));else await writePrivateManifest(f.manifestPath,f.m,{...f,replace:true});await expect(executeIsolationVerification(f,f.dependencies as any)).rejects.toThrow('Issue #29:');if(fault!=='source-target-collision')expect((await readPrivateManifest(f.manifestPath,f)).history.some(h=>h.resourceId?.startsWith('isolation:'))).toBe(false);});
