import { expect,test } from 'vitest';
import { verifyTargetAuthPrivacy } from '../../scripts/issue29-operations/target-integrity.mjs';
import { manifestFixture } from '../fixtures/issue29-operations';
test('refuses preserved target identity before any Auth/privacy request',async()=>{const manifest=structuredClone(manifestFixture());manifest.target!.ref=manifest.preservedRefs[0];let called=false;await expect(verifyTargetAuthPrivacy({manifest,publicKey:'private',sourceSessionProof:{} as never,oldSourceAccessToken:'private',actors:[],restoredAt:'2026-09-05T12:00:00.000Z',fetchImpl:async()=>{called=true;return new Response();}})).rejects.toThrow('TARGET_FORBIDDEN');expect(called).toBe(false);});
import { captureSourceSessionProof } from '../../scripts/issue29-operations/target-integrity.mjs';
const now='2026-09-05T12:02:00.000Z',restoredAt='2026-09-05T12:01:00.000Z';
function token(ref:string,id:string,issued='2026-09-05T12:01:05.000Z'){return [Buffer.from(JSON.stringify({alg:'ES256',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({iss:`https://${ref}.supabase.co/auth/v1`,sub:id,role:'authenticated',aud:'authenticated',session_id:ref.startsWith('a')?'99999999-9999-4999-8999-999999999999':id,iat:Date.parse(issued)/1000,exp:Date.parse(now)/1000+3600,aal:'aal1'})).toString('base64url'),'c2lnbmF0dXJl'].join('.');}
function fixture(){const manifest=structuredClone(manifestFixture());manifest.state='storage_restored';manifest.cleanup.resources=[{provider:'supabase',id:manifest.source!.ref,runId:manifest.runId,createdAt:now,evidenceSha256:'a'.repeat(64),disposition:'persistent',absentAt:null},{provider:'supabase',id:manifest.target!.ref,runId:manifest.runId,createdAt:now,evidenceSha256:'a'.repeat(64),disposition:'disposable',absentAt:null}];manifest.history.push({step:'restore-database',operationId:manifest.runId,resourceId:manifest.target!.ref,completedAt:restoredAt,evidenceSha256:'a'.repeat(64)},{step:'restore-storage',operationId:manifest.runId,resourceId:manifest.target!.ref,completedAt:restoredAt,evidenceSha256:'a'.repeat(64)});const actors=['seller','buyer','outsider','future-staff'].map((alias,i)=>({alias,id:`${i+1}1111111-1111-4111-8111-111111111111`,accessToken:''}));for(const a of actors)a.accessToken=token(manifest.target!.ref,a.id);return{manifest,actors};}
test('accepts only freshly issued target sessions and actual rejection of a still-valid independently observed source token',async()=>{
 const {manifest,actors}=fixture(),old=token(manifest.source!.ref,actors[0].id,'2026-09-05T12:00:00.000Z');const reads:string[]=[];const fetchImpl=async(url:string|URL|Request,init?:RequestInit)=>{reads.push(String(url));expect(init?.method).toBe('GET');expect(init?.redirect).toBe('error');const supplied=String(new Headers(init?.headers).get('authorization')).slice(7);if(String(url).includes(manifest.target!.ref)&&supplied===old)return Response.json({message:'private-provider-body'},{status:403});const claims=JSON.parse(Buffer.from(supplied.split('.')[1],'base64url').toString());return Response.json({id:claims.sub,app_metadata:{issue29_run_id:manifest.runId},last_sign_in_at:'2026-09-05T12:01:05.000Z',email:'private@example.invalid'});};
 const sourceSessionProof=await captureSourceSessionProof({manifest,publicKey:'private-public-key',accessToken:old,actor:actors[0],fetchImpl,now:'2026-09-05T12:00:30.000Z'});const proof=await verifyTargetAuthPrivacy({manifest,publicKey:'private-public-key',sourceSessionProof,oldSourceAccessToken:old,actors,restoredAt,fetchImpl,now});expect(proof!.oldSourceTokenDenied).toBe(true);expect(proof!.actors.map((a:any)=>a.alias)).toEqual(['seller','buyer','outsider','future-staff']);expect(JSON.stringify(proof)).not.toContain('private@example.invalid');expect(JSON.stringify(proof)).not.toContain(actors[0].id);expect(reads.filter(u=>u.includes(manifest.target!.ref))).toHaveLength(5);
});
import { validateTargetTap } from '../../scripts/issue29-operations/target-integrity.mjs';
test('reused pgTAP evidence requires exact nonzero discovery and never exposes failed private diagnostics',()=>{const name='cross_user_privacy.pgtap.sql',hash='a'.repeat(64);expect(validateTargetTap('1..2\nok 1 - allowed\nok 2 - denied\n',name,hash).testCount).toBe(2);for(const text of ['1..0\n','1..2\nok 1 - passed\nnot ok 2 - private contents\n','1..2\nok 1 - duplicate\nok 1 - duplicate\n'])expect(()=>validateTargetTap(text,name,hash)).toThrow('DATABASE_CONTRACT_FAILED');});
test.each(['accepted-source','wrong-issuer','stale-target-session','wrong-actor','required-mfa'])('rejects %s without disclosing credentials or provider bodies',async kind=>{
 const {manifest,actors}=fixture(),old=token(manifest.source!.ref,actors[0].id,'2026-09-05T12:00:00.000Z');const sourceFetch=async()=>Response.json({id:actors[0].id,app_metadata:{issue29_run_id:manifest.runId}});const sourceSessionProof=await captureSourceSessionProof({manifest,publicKey:'public',accessToken:old,actor:actors[0],fetchImpl:sourceFetch,now:'2026-09-05T12:00:30.000Z'});
 if(kind==='wrong-issuer')actors[0].accessToken=old;if(kind==='stale-target-session')actors[0].accessToken=token(manifest.target!.ref,actors[0].id,'2026-09-05T12:00:00.000Z');if(kind==='required-mfa')Object.assign(actors[3],{requiredAal:'aal2'});
 const fetchImpl=async(_url:string|URL|Request,init?:RequestInit)=>{const supplied=String(new Headers(init?.headers).get('authorization')).slice(7);if(supplied===old)return Response.json({private:'provider body'},{status:kind==='accepted-source'?200:403});const claims=JSON.parse(Buffer.from(supplied.split('.')[1],'base64url').toString());return Response.json({id:kind==='wrong-actor'?'wrong-user':claims.sub,app_metadata:{issue29_run_id:manifest.runId},last_sign_in_at:'2026-09-05T12:01:05.000Z',email:'private@example.invalid'});};
 await expect(verifyTargetAuthPrivacy({manifest,publicKey:'public',sourceSessionProof,oldSourceAccessToken:old,actors,restoredAt,fetchImpl,now})).rejects.toThrow('Issue #29:');
});

test('retains exact original TAP bytes privately by output hash before returning the parsed receipt',async()=>{
 const{mkdtemp,readFile,stat,rm}=await import('node:fs/promises');const{join}=await import('node:path');const{tmpdir}=await import('node:os');const{persistTargetTap}=await import('../../scripts/issue29-operations/target-integrity.mjs');const dir=await mkdtemp(join(tmpdir(),'issue29-target-tap-'));try{const output='1..2\nok 1 - owner access\nok 2 - cross-user denied\n';const proof=await persistTargetTap({manifestPath:join(dir,'manifest.json'),repositoryRoot:process.cwd(),output,name:'cross_user_privacy.pgtap.sql',sourceSha256:'a'.repeat(64)});const path=join(dir,`${proof.outputSha256}.tap`);expect(await readFile(path,'utf8')).toBe(output);expect((await stat(path)).mode&0o777).toBe(0o600);expect(proof.testCount).toBe(2);await expect(persistTargetTap({manifestPath:join(dir,'manifest.json'),repositoryRoot:process.cwd(),output:'1..1\nnot ok 1 - private fixture diagnostic\n',name:'cross_user_privacy.pgtap.sql',sourceSha256:'a'.repeat(64)})).rejects.toThrow('DATABASE_CONTRACT_FAILED');}finally{await rm(dir,{recursive:true,force:true});}
});
