import { afterEach, expect, it, vi } from 'vitest';
import { mkdtemp,writeFile,rm,readFile } from 'node:fs/promises';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {manifestFixture,candidate} from '../fixtures/issue29-operations';
import {writePrivateManifest,readPrivateManifest} from '../../scripts/issue29-operations/manifest.mjs';
import {executeRestore} from '../../scripts/issue29-operations/restore-execution.mjs';
import {canonicalJson} from '../../scripts/issue29-operations/recovery-set.mjs';
import {createSentinelAdapter} from '../../scripts/issue29-operations/incident-adapter.mjs';
import {createHash} from 'node:crypto';
const now='2026-09-05T12:01:00.000Z';const dirs:string[]=[];
afterEach(async()=>{vi.doUnmock('../../scripts/issue29-operations/logical-recovery.mjs');vi.doUnmock('../../scripts/issue29-operations/recovery-set.mjs');vi.doUnmock('../../scripts/issue29-operations/storage-adapter.mjs');vi.doUnmock('../../scripts/issue29-operations/quarantine.mjs');vi.resetModules();await Promise.all(dirs.splice(0).map(p=>rm(p,{recursive:true,force:true})));});
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'issue29-restore-execution-'));dirs.push(dir);const manifest=manifestFixture();manifest.state='target_read_back';manifest.backupVerification={descriptorSha256:'d'.repeat(64),independentlyVerifiedAt:now,sourceReadsComplete:true};manifest.cleanup.resources.push({provider:'supabase',id:manifest.target!.ref,runId:manifest.runId,createdAt:now,evidenceSha256:'e'.repeat(64),disposition:'disposable',absentAt:null});const manifestPath=join(dir,'manifest.json');const settingsPath=join(dir,'settings.json');const settings={schemaVersion:1,operation:'restore',providerToken:'private-provider-token',targetServiceKey:'private-service-key',backupDirectory:join(dir,'backup'),descriptorSha256:'d'.repeat(64),privateKeyPath:join(dir,'private.pem'),connection:{host:`db.${manifest.target!.ref}.supabase.co`,port:5432,database:'postgres',user:'postgres',password:'private-password',sslmode:'verify-full'},toolchain:{mode:'container'}};await writePrivateManifest(manifestPath,manifest,{repositoryRoot:process.cwd(),candidate,now});await writeFile(settingsPath,JSON.stringify(settings),{mode:0o600});return{manifest,manifestPath,settingsPath,settings};}
it.each(['unowned','no-backup','wrong-backup','wrong-state','verify-before-restore','private-settings'])('rejects %s before any provider or database write',async kind=>{
 const f=await fixture();if(kind==='unowned')f.manifest.cleanup.resources=[];if(kind==='no-backup')f.manifest.backupVerification=null;if(kind==='wrong-backup')f.settings.descriptorSha256='f'.repeat(64);if(kind==='wrong-state')f.manifest.state='backup_verified';if(kind==='private-settings')(f.settings as any).productionSecret='must-not-copy';await writePrivateManifest(f.manifestPath,f.manifest,{repositoryRoot:process.cwd(),candidate,now,replace:true});await writeFile(f.settingsPath,JSON.stringify(f.settings),{mode:0o600});
 await expect(executeRestore({...f,repositoryRoot:process.cwd(),candidate,now,verifyOnly:kind==='verify-before-restore'})).rejects.toThrow('Issue #29:');expect((await readPrivateManifest(f.manifestPath,{repositoryRoot:process.cwd(),now})).pending).toBeNull();
});
it('rejects a checkpoint older than 24 hours even when encryption finished just before restore',async()=>{
 const f=await fixture();const {generateKeyPairSync}=await import('node:crypto');const {createRecoverySet}=await import('../../scripts/issue29-operations/recovery-set.mjs');const keys=generateKeyPairSync('rsa',{modulusLength:3072});
 const checkpoint={snapshotId:'snapshot-fixture',finalizedRowsetSha256:'d'.repeat(64)},source=f.manifest.source!;
 const made=await createRecoverySet({destination:f.settings.backupDirectory,repositoryRoot:process.cwd(),publicKey:keys.publicKey,components:new Map(['roles.sql','schema.sql','data.sql','migration-history.sql','auth-recovery.sql','managed-schema.sql','platform-inventory.json'].map(name=>[name,Buffer.from(name==='platform-inventory.json'?'{}':'-- synthetic')])),storageManifest:{bucket:'listing-images',files:[]},checkpointBefore:checkpoint,checkpointAfter:checkpoint,metadata:{backupSetId:f.manifest.runId,source:{environmentAlias:f.manifest.fixture.alias,organizationId:source.organizationId,projectRef:source.ref,region:source.region,classification:source.classification},release:{commitSha:candidate.sha,treeSha:candidate.tree,workerVersion:candidate.deploymentId},startedAt:'2026-09-04T12:00:00.000Z',finishedAt:now,tools:{supabaseCli:'2.109.1',postgres:'17.6',operator:'issue29-v2'},migration:{count:27,sha256:'e'.repeat(64)},destinationAlias:f.manifest.backup.destinationAlias,exclusions:['auth-sessions'],manualReconstruction:['runtime-secrets']}});
 f.manifest.backupVerification!.descriptorSha256=made.descriptorSha256;f.settings.descriptorSha256=made.descriptorSha256;await writePrivateManifest(f.manifestPath,f.manifest,{repositoryRoot:process.cwd(),candidate,now,replace:true});await writeFile(f.settingsPath,JSON.stringify(f.settings));await writeFile(f.settings.privateKeyPath,keys.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});
 await expect(executeRestore({...f,repositoryRoot:process.cwd(),candidate,now})).rejects.toThrow('BACKUP_RPO_EXCEEDED');const m=await readPrivateManifest(f.manifestPath,{repositoryRoot:process.cwd(),now});expect(m.pending).toBeNull();expect(m.recoveryTimings).toBeUndefined();
});
async function runSentinelCoordinator(mode:'existing'|'wrong-hash'|'missing-logical'|'wrong-logical-target'|'wrong-logical-time'|'corrupt-logical-proof'|'resumed'|'wrong-resume-proof'='existing',createBucket=false){
 const f=await fixture(),bucket={id:'operations-sentinels',name:'operations-sentinels',public:false,file_size_limit:4096,allowed_mime_types:['application/octet-stream']},bucketHash=createHash('sha256').update(canonicalJson(bucket)).digest('hex');
 const preexisting=['missing-logical','wrong-logical-target','wrong-logical-time','corrupt-logical-proof','resumed','wrong-resume-proof'].includes(mode);
 f.manifest.recoveryTimings=preexisting?{startedAt:now,databaseVerifiedAt:now}:{startedAt:now};if(preexisting)f.manifest.state='database_restored';
 if(preexisting&&mode!=='missing-logical'){
  const bytes=Buffer.from(canonicalJson({verified:true})),hash=createHash('sha256').update(bytes).digest('hex');
  await writeFile(join(f.manifestPath.replace(/\/manifest\.json$/u,''),`${hash}.json`),mode==='corrupt-logical-proof'?'{}':bytes,{mode:0o600});
  f.manifest.history.push({step:'restore-database',operationId:f.manifest.runId,completedAt:mode==='wrong-logical-time'?'2026-09-05T12:00:59.999Z':now,resourceId:mode==='wrong-logical-target'?f.manifest.source!.ref:f.manifest.target!.ref,evidenceSha256:hash});
  if(mode==='resumed'||mode==='wrong-resume-proof'){
   const id=`storage-bucket:${f.manifest.target!.ref}:operations-sentinels`,proof={targetRef:f.manifest.target!.ref,descriptorSha256:f.settings.descriptorSha256,logicalRestoreEvidenceSha256:mode==='wrong-resume-proof'?'f'.repeat(64):hash,intent:{kind:'bucket-create',resource:'operations-sentinels',sha256:bucketHash},bucket},body=Buffer.from(canonicalJson(proof)),proofHash=createHash('sha256').update(body).digest('hex');
   await writeFile(join(f.manifestPath.replace(/\/manifest\.json$/u,''),`${proofHash}.json`),body,{mode:0o600});
   f.manifest.history.push({step:'restore-storage',operationId:f.manifest.runId,completedAt:now,resourceId:id,evidenceSha256:proofHash});
   f.manifest.cleanup.resources.push({provider:'supabase-storage',id,runId:f.manifest.runId,createdAt:now,evidenceSha256:proofHash,disposition:'disposable',absentAt:null});
  }
 }
 await writePrivateManifest(f.manifestPath,f.manifest,{repositoryRoot:process.cwd(),candidate,now,replace:true});await writeFile(f.settings.privateKeyPath,'private-fixture-key',{mode:0o600});
 const platform={managedBaselineSha256:'a'.repeat(64),storageBuckets:[bucket]};
 vi.resetModules();
 vi.doMock('../../scripts/issue29-operations/recovery-set.mjs',async importOriginal=>({...await importOriginal(),withVerifiedRecoverySet:async(_options:any,callback:any)=>callback({descriptor:{metadata:{source:{projectRef:f.manifest.source!.ref},release:{commitSha:candidate.sha,treeSha:candidate.tree,workerVersion:candidate.deploymentId},startedAt:'2026-09-05T12:00:00.000Z'},checkpoint:{finalizedRowsetSha256:'d'.repeat(64)}},components:new Map([['platform-inventory.json',Buffer.from(JSON.stringify(platform))]]),storageManifest:{bucket:'listing-images',files:[]}})}));
 vi.doMock('../../scripts/issue29-operations/logical-recovery.mjs',async importOriginal=>({...await importOriginal(),captureManagedBaseline:async()=>({schemaSha256:'a'.repeat(64)}),restoreLogicalRecovery:async()=>{},verifyLogicalRecovery:async()=>({}),readFinalizedPhotos:async()=>[]}));
 vi.doMock('../../scripts/issue29-operations/quarantine.mjs',()=>({readRestoreQuarantine:async()=>({evidence:'fixture',quarantine:{}})}));
 const storageRestore=vi.fn(async(options:any)=>{const intent={kind:'bucket-create',resource:'operations-sentinels',sha256:mode==='wrong-hash'?'f'.repeat(64):bucketHash};if(createBucket)await options.persistIntent(intent);await options.readbackVerified(intent);return{status:'verified'};});
 vi.doMock('../../scripts/issue29-operations/storage-adapter.mjs',()=>({restoreFinalizedStorage:storageRestore,verifyFinalizedStorage:async()=>({status:'verified'})}));
 const {executeRestore:run}=await import('../../scripts/issue29-operations/restore-execution.mjs');
 return{f,bucket,bucketHash,run,storageRestore};
}
it('persists exact logical-restore-bound ownership for an existing recovered sentinel bucket before target upload',async()=>{
 let tick=0;const clock=()=>new Date(Date.parse(now)+tick++*100).toISOString();
 const {f,bucket,run}=await runSentinelCoordinator();await run({...f,repositoryRoot:process.cwd(),candidate,clock});const restored=await readPrivateManifest(f.manifestPath,{repositoryRoot:process.cwd(),candidate,now:clock()});const id=`storage-bucket:${restored.target!.ref}:operations-sentinels`,owned=restored.cleanup.resources.find(resource=>resource.id===id)!;
 expect(owned).toMatchObject({provider:'supabase-storage',runId:restored.runId,disposition:'disposable',absentAt:null});const proof=JSON.parse(await readFile(join(f.manifestPath.replace(/\/manifest\.json$/u,''),`${owned.evidenceSha256}.json`),'utf8')),logical=restored.history.find(entry=>entry.step==='restore-database'&&entry.resourceId===restored.target!.ref)!;
 expect(proof).toMatchObject({targetRef:restored.target!.ref,descriptorSha256:f.settings.descriptorSha256,logicalRestoreEvidenceSha256:logical.evidenceSha256,bucket});
 expect(logical.completedAt).toBe(restored.recoveryTimings!.databaseVerifiedAt);expect(logical.completedAt).not.toBe(now);
 let object:Uint8Array|null=null;const bytes=Buffer.from('sentinel'),hash=createHash('sha256').update(bytes).digest('hex');const fetchImpl:typeof fetch=async(url,init)=>{const u=new URL(String(url)),method=init?.method??'GET';if(u.hostname==='api.supabase.com'){if(u.pathname.includes('/organizations/'))return Response.json({id:restored.target!.organizationId,plan:'free'});if(u.pathname.endsWith('/api-keys'))return Response.json([{name:'service_role',api_key:'private-service-key'}]);return Response.json({ref:restored.target!.ref,organization_slug:restored.target!.organizationId,region:restored.target!.region,status:'ACTIVE_HEALTHY',database:{version:'17.6.1'}});}if(u.pathname==='/storage/v1/bucket/operations-sentinels')return Response.json(bucket);if(method==='POST'&&u.pathname.startsWith('/storage/v1/object/')){object=new Uint8Array(init?.body as Uint8Array);return Response.json({Key:'owned'});}if(u.pathname.startsWith('/storage/v1/object/')){if(!object)return Response.json({message:'missing',statusCode:'404'},{status:404});const owned=new ArrayBuffer(object.byteLength);new Uint8Array(owned).set(object);return new Response(owned);}return Response.json({message:'missing'},{status:404});};
 const sentinel=createSentinelAdapter({manifest:restored,projectRef:restored.target!.ref,providerToken:'private-provider-token',serviceKey:'private-service-key',sentinel:{path:`${restored.runId}/sentinel.bin`,sha256:hash,bytes},readinessOrigin:`https://issue29-restore-${restored.runId}.owner.workers.dev`,monitorToken:'dedicated-monitor-token-12345678901234567890123456'},{now:clock,fetchImpl});const upload=sentinel.operation('upload');await upload.inspect();await upload.mutate();expect(await upload.readback()).toMatchObject({status:'verified',sha256:hash});
});
it('refuses a sentinel callback with the wrong recovered configuration hash or without exact logical restore provenance',async()=>{
 const wrong=await runSentinelCoordinator('wrong-hash');await expect(wrong.run({...wrong.f,repositoryRoot:process.cwd(),candidate,now})).rejects.toThrow('SENTINEL_BUCKET_RESTORE_OWNERSHIP_REQUIRED');
 const missing=await runSentinelCoordinator('missing-logical');await expect(missing.run({...missing.f,repositoryRoot:process.cwd(),candidate,now})).rejects.toThrow('SENTINEL_BUCKET_RESTORE_OWNERSHIP_REQUIRED');
});
it('requires the same verified logical event for normal bucket creation with an advancing clock',async()=>{
 const {f,run,storageRestore}=await runSentinelCoordinator('existing',true);let tick=0;const clock=()=>new Date(Date.parse(now)+tick++*100).toISOString();await run({...f,repositoryRoot:process.cwd(),candidate,clock});
 const m=await readPrivateManifest(f.manifestPath,{repositoryRoot:process.cwd(),candidate,now:clock()}),logical=m.history.find(h=>h.step==='restore-database')!,owned=m.cleanup.resources.find(r=>r.id===`storage-bucket:${m.target!.ref}:operations-sentinels`)!;
 expect(storageRestore).toHaveBeenCalledOnce();expect(logical.completedAt).toBe(m.recoveryTimings!.databaseVerifiedAt);expect(owned.evidenceSha256).toMatch(/^[a-f0-9]{64}$/u);expect(m.pending).toBeNull();
 const proof=JSON.parse(await readFile(join(f.manifestPath.replace(/\/manifest\.json$/u,''),`${owned.evidenceSha256}.json`),'utf8'));expect(proof.logicalRestoreEvidenceSha256).toBe(logical.evidenceSha256);
});
it.each(['missing-logical','wrong-logical-target','wrong-logical-time','corrupt-logical-proof'] as const)('refuses %s before normal bucket creation or ownership persistence',async mode=>{
 const {f,run,storageRestore}=await runSentinelCoordinator(mode,true);await expect(run({...f,repositoryRoot:process.cwd(),candidate,now})).rejects.toThrow('SENTINEL_BUCKET_RESTORE_OWNERSHIP_REQUIRED');
 expect(storageRestore).not.toHaveBeenCalled();const m=await readPrivateManifest(f.manifestPath,{repositoryRoot:process.cwd(),candidate,now});expect(m.pending).toBeNull();expect(m.cleanup.resources.some(r=>r.provider==='supabase-storage')).toBe(false);expect(m.history.some(h=>h.step==='restore-storage')).toBe(false);
});
it('reuses only existing sentinel ownership bound to the same immutable logical restore proof',async()=>{
 const valid=await runSentinelCoordinator('resumed');await expect(valid.run({...valid.f,repositoryRoot:process.cwd(),candidate,now})).resolves.toMatchObject({status:'DATABASE_STORAGE_VERIFIED_APPLICATION_PROOF_PENDING'});
 const wrong=await runSentinelCoordinator('wrong-resume-proof');await expect(wrong.run({...wrong.f,repositoryRoot:process.cwd(),candidate,now})).rejects.toThrow('SENTINEL_BUCKET_RESTORE_OWNERSHIP_REQUIRED');
});
