import {persistOperationsIntent} from '../../scripts/issue29-operations/operator.mjs';
import {afterEach,expect,it,vi} from 'vitest';
import {mkdtemp,writeFile,readFile,rm,chmod} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {executeMaintenanceCommand} from '../../scripts/issue29-operations/maintenance-execution.mjs';
import {canonicalJson} from '../../scripts/issue29-operations/recovery-set.mjs';
import {sourceIdentitySha256} from '../../scripts/issue29-operations/supabase-adapter.mjs';
import {readPrivateManifest,writePrivateManifest} from '../../scripts/issue29-operations/manifest.mjs';
import {manifestFixture,maintenanceFixture} from '../fixtures/issue29-operations';
const dirs:string[]=[];const now='2026-09-05T12:01:00.000Z';
const hash=(v:unknown)=>createHash('sha256').update(canonicalJson(v)).digest('hex');
afterEach(async()=>{for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
async function fixture(){const d=await mkdtemp(join(tmpdir(),'issue29-maintenance-gateway-'));dirs.push(d);const m=manifestFixture();m.target=null;m.state='source_pause_pending';m.allowedActions.push('pause-source');m.backupVerification={descriptorSha256:'a'.repeat(64),independentlyVerifiedAt:now,sourceReadsComplete:true};m.cleanup.resources.push({provider:'supabase',id:m.source!.ref,runId:m.runId,createdAt:now,evidenceSha256:'a'.repeat(64),disposition:'persistent',absentAt:null});m.maintenance=maintenanceFixture(m,now);m.maintenance.phase='pause_pending';m.maintenance.pausedAt=null;m.maintenance.pauseReadbackSha256=null;m.maintenance.preservation.identitySha256=sourceIdentitySha256(m.source!);m.pending={step:'pause-source',resourceId:m.source!.ref,operationId:m.runId,startedAt:now,priorStateSha256:hash(m.maintenance.preservation)};m.attempts['pause-source']=1;
 const manifestPath=join(d,'manifest.json'),settingsPath=join(d,'settings.json');const settings={schemaVersion:1,operation:'pause-source',providerToken:'private-management-token',capabilityId:m.capabilityIds['restore-write'],sourceSettingsPath:join(d,'source.json'),bindingSettingsPath:join(d,'binding.json'),monitorToken:'x'.repeat(43),sourceWorker:{settings:{},privateDirectory:d,readToken:'private-read-token'}};await writePrivateManifest(manifestPath,m,{repositoryRoot:process.cwd(),now});await persistOperationsIntent(manifestPath,m,process.cwd());await writeFile(settingsPath,JSON.stringify(settings),{mode:0o600});return{d,m,settings,manifestPath,settingsPath,repositoryRoot:process.cwd(),candidate:m.candidate,operation:'pause-source',now};}
it('persists actual paused readback bytes before advancing and never repeats a pending pause',async()=>{const f=await fixture();const evidence={projectRef:f.m.source!.ref,status:'INACTIVE',identitySha256:sourceIdentitySha256(f.m.source!),preservationSha256:hash(f.m.maintenance!.preservation),checkedAt:now,configurationObserved:false};const pause=vi.fn();const providerFactory=()=>({pauseSource:pause,readPaused:async()=>({project:f.m.source!,...evidence,evidence,evidenceSha256:hash(evidence)})});const result=await executeMaintenanceCommand(f,{providerFactory} as any);expect(result.phase).toBe('paused');expect(pause).not.toHaveBeenCalled();expect(await readFile(join(f.d,hash(evidence)+'.json'),'utf8')).toBe(canonicalJson(evidence));expect((await readPrivateManifest(f.manifestPath,f)).maintenance?.pauseReadbackSha256).toBe(hash(evidence));expect(JSON.stringify(result)).not.toContain('private-management-token');});
it('does not advance an ambiguous pending pause on fabricated readback hash',async()=>{const f=await fixture();const evidence={projectRef:f.m.source!.ref,status:'INACTIVE',identitySha256:sourceIdentitySha256(f.m.source!),preservationSha256:hash(f.m.maintenance!.preservation),checkedAt:now,configurationObserved:false};const providerFactory=()=>({readPaused:async()=>({project:f.m.source!,...evidence,evidence,evidenceSha256:'b'.repeat(64)})});await expect(executeMaintenanceCommand(f,{providerFactory} as any)).rejects.toThrow('Issue #29:');expect((await readPrivateManifest(f.manifestPath,f)).pending?.step).toBe('pause-source');});
it.each(['operation','role','public-file','unknown-field'])('rejects %s before provider access',async reason=>{const f=await fixture();if(reason==='operation')f.operation='resume-source';if(reason==='role')f.settings.capabilityId='source-key';if(reason==='unknown-field')(f.settings as any).allowPreserved=true;await writeFile(f.settingsPath,JSON.stringify(f.settings));if(reason==='public-file')await chmod(f.settingsPath,0o644);const providerFactory=vi.fn();await expect(executeMaintenanceCommand(f,{providerFactory} as any)).rejects.toThrow('Issue #29:');expect(providerFactory).not.toHaveBeenCalled();});

async function verifiedRecoveryFixture(){
 const f=await fixture();const {generateKeyPairSync}=await import('node:crypto');const {createRecoverySet,readRecoveryDescriptor}=await import('../../scripts/issue29-operations/recovery-set.mjs');const {executeBackupVerification,executeBackupCopy}=await import('../../scripts/issue29-operations/execution.mjs');
 const keys=generateKeyPairSync('rsa',{modulusLength:3072}),source=f.m.source!;f.m.state='backup_started';f.m.maintenance=null;f.m.pending=null;f.m.attempts={};f.m.allowedActions.push('authorize-maintenance','artifact-upload');f.m.backup.publicKeyId=createHash('sha256').update(keys.publicKey.export({type:'spki',format:'der'})).digest('hex');
 const directory=join(f.d,'encrypted'),privateKeyPath=join(f.d,'private.pem');await writeFile(privateKeyPath,keys.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});
 const platform={auth:{users:4,identities:4,sha256:'e'.repeat(64)},tables:[{name:'profiles',count:4}],managedBaselineSha256:'b'.repeat(64)},checkpoint={snapshotId:'00000003-00000001-1',finalizedRowsetSha256:'d'.repeat(64)},migration={count:27,sha256:'a'.repeat(64)};
 const components=new Map(['roles.sql','schema.sql','data.sql','migration-history.sql','auth-recovery.sql','managed-schema.sql'].map(n=>[n,Buffer.from(`synthetic-${n}`)]));components.set('platform-inventory.json',Buffer.from(JSON.stringify(platform)));
 const backup=await createRecoverySet({destination:directory,repositoryRoot:f.repositoryRoot,publicKey:keys.publicKey,components,checkpointBefore:checkpoint,checkpointAfter:checkpoint,storageManifest:{bucket:'listing-images',files:[]},metadata:{backupSetId:f.m.runId,source:{environmentAlias:f.m.fixture.alias,organizationId:source.organizationId,projectRef:source.ref,region:source.region,classification:source.classification},release:{commitSha:f.candidate.sha,treeSha:f.candidate.tree,workerVersion:f.candidate.deploymentId},startedAt:'2026-09-05T12:00:00.000Z',finishedAt:now,tools:{supabaseCli:'2.109.1',postgres:'17.6',operator:'issue29-v2'},migration,destinationAlias:f.m.backup.destinationAlias,exclusions:['auth-sessions'],manualReconstruction:['runtime-secrets']}});
 f.m.history.push({step:'backup-set',operationId:f.m.runId,completedAt:now,resourceId:null,evidenceSha256:backup.descriptorSha256});await writePrivateManifest(f.manifestPath,f.m,{...f,replace:true});
 await executeBackupVerification({...f,directory,privateKeyPath,expectedDescriptorSha256:backup.descriptorSha256});
 const destination=join(f.d,'owner-copy');await writeFile(f.settingsPath,JSON.stringify({schemaVersion:1,operation:'copy-backup',directory,destination,descriptorSha256:backup.descriptorSha256,destinationAlias:'owner-secondary',retentionDays:35,capabilityId:f.m.capabilityIds['artifact-upload']}));const copied=await executeBackupCopy(f);
 const descriptor=await readRecoveryDescriptor({directory,repositoryRoot:f.repositoryRoot,expectedDescriptorSha256:backup.descriptorSha256});
 const provenance={runId:f.m.runId,projectRef:source.ref,createdResourceEvidenceSha256:f.m.sourceProvenance!.creationReadbackSha256,classification:'synthetic-owner-controlled',authUsers:4,authIdentities:4,authInventorySha256:platform.auth.sha256,applicationInventorySha256:hash(platform.tables),applicationTableCount:1,migration,managedBaselineSha256:platform.managedBaselineSha256,finalizedRowsetSha256:checkpoint.finalizedRowsetSha256,storageObjectCount:0,storagePathTreeSha256:descriptor.storage.pathTreeSha256,storageBytes:0};
 const proof={checkedAt:now,identitySha256:sourceIdentitySha256(source),configSha256:'b'.repeat(64),provenanceSha256:hash(provenance),workerSha256:'c'.repeat(64),checkpointSha256:hash(checkpoint),readinessSha256:'d'.repeat(64),evidenceSha256:'e'.repeat(64)};
 const settings={...f.settings,operation:'authorize-maintenance',window:{id:f.m.runId,expiresAt:'2026-09-05T13:00:00.000Z'},backup:{directory,descriptorSha256:backup.descriptorSha256,privateKeyPath,artifact:{provider:'owner-encrypted-retention',directory:destination,copyEvidenceSha256:copied.evidenceSha256}}};await writeFile(f.settingsPath,JSON.stringify(settings));
 return{...f,operation:'authorize-maintenance',settings,proof};
}
it('authorizes source maintenance only after decrypting both current retained encrypted copies',async()=>{
 const f=await verifiedRecoveryFixture();const pauseSource=vi.fn(),verifyArtifact=vi.fn();const result=await executeMaintenanceCommand(f,{providerFactory:()=>({pauseSource}),inspectSource:async()=>f.proof,verifyArtifact} as any);
 expect(result.phase).toBe('authorized');expect(pauseSource).not.toHaveBeenCalled();expect(verifyArtifact).not.toHaveBeenCalled();const m=await readPrivateManifest(f.manifestPath,f);expect(m.pending).toBeNull();expect(m.maintenance?.backup.checkpointSha256).toBe(f.proof.checkpointSha256);
 const artifact=JSON.parse(await readFile(join(f.d,m.maintenance!.backup.artifactSha256+'.json'),'utf8'));expect(artifact.workflowProof).toBe(false);expect(artifact.retentionDays).toBe(35);expect(artifact.encryptedOnly).toBe(true);expect(artifact.recovery.descriptorSha256).toBe(f.settings.backup.descriptorSha256);
});
it.each(['corrupt-copy','checkpoint-drift','colocated-key'])('rejects %s before authorizing maintenance or pausing source',async problem=>{
 const f=await verifiedRecoveryFixture();if(problem==='corrupt-copy')await writeFile(join(f.settings.backup.artifact.directory,'component-000000.bin'),'corrupt');if(problem==='checkpoint-drift')f.proof.provenanceSha256='f'.repeat(64);if(problem==='colocated-key'){const key=await readFile(f.settings.backup.privateKeyPath);f.settings.backup.privateKeyPath=join(f.settings.backup.artifact.directory,'key.pem');await writeFile(f.settings.backup.privateKeyPath,key,{mode:0o600});key.fill(0);await writeFile(f.settingsPath,JSON.stringify(f.settings));}
 const pauseSource=vi.fn();await expect(executeMaintenanceCommand(f,{providerFactory:()=>({pauseSource}),inspectSource:async()=>f.proof} as any)).rejects.toThrow('Issue #29:');expect(pauseSource).not.toHaveBeenCalled();const m=await readPrivateManifest(f.manifestPath,f);expect(m.maintenance).toBeNull();expect(m.pending).toBeNull();
});
