import { describe, expect, it } from 'vitest';
import { createMonitorAdapter, MONITOR_SIGNALS } from '../../scripts/issue29-operations/monitor-adapter.mjs';

const now='2026-09-08T12:00:00.000Z',secretHash='0badb513f9e2c6f69084754fbf2bae5f0b1aed5247b16bff099dfb213881f9cd';
const c={workerAlias:'aromatika-issue29-monitor',origin:'https://aromatika-issue29-monitor.example.workers.dev',targetOrigin:'https://issue29-source.example.workers.dev',environmentAlias:'development',runtimeEnvironment:'development' as const,candidateSha:'a'.repeat(40),runId:'45454545-4545-4454-8454-454545454545',webhookSigningSecretSha256:secretHash,evidenceReadToken:'e'.repeat(43),watchdogToken:'w'.repeat(43),backupCheckpointToken:'b'.repeat(43),maintenanceToken:'m'.repeat(43)};
const cp={checkpointAt:'2026-09-08T11:00:00.000Z',descriptorSha256:'d'.repeat(64),artifactSha256:'c'.repeat(64)};
const config=(v:typeof c&{configSha256?:string,releaseAdoptionToken?:string}=c)=>({schemaVersion:1,environment:v.environmentAlias,runtimeEnvironment:v.runtimeEnvironment,targetOrigin:v.targetOrigin,release:v.candidateSha,signalFamilies:MONITOR_SIGNALS,scheduleMinutes:10,configSha256:'f'.repeat(64),webhookSigningSecretSha256:v.webhookSigningSecretSha256});
const state=(v=c,extra={})=>({schemaVersion:1,environment:v.environmentAlias,release:v.candidateSha,observedTargetOrigin:v.targetOrigin,lastSuccessfulMonitorCycleAt:now,lastCompletedMonitorCycleAt:now,latestTrustedBackupCheckpointAt:cp.checkpointAt,latestTrustedBackupDescriptorSha256:cp.descriptorSha256,latestTrustedBackupArtifactSha256:cp.artifactSha256,integrityFailureEvidenceSha256:null,maintenance:null,signals:MONITOR_SIGNALS.map(signal=>({signal,ok:true,severity:'none',reasonCode:'healthy',checkedAt:now})),...extra});
function adapter(fetchImpl:typeof fetch,input:typeof c&{configSha256?:string,releaseAdoptionToken?:string}=c){return createMonitorAdapter(input,{fetchImpl,now:()=>now});}

describe('Issue 29 Cloudflare monitor operator adapter',()=>{
 it('binds all nine signals, static Worker configuration, and its signing-secret digest',async()=>{const fetchImpl:typeof fetch=async url=>{const path=new URL(String(url)).pathname;if(path==='/ops/monitor/config')return Response.json(config());if(path==='/ops/monitor/state')return Response.json(state());if(path==='/ops/monitor/heartbeat'){const {signals,...value}=state();return Response.json(value);}return Response.json({ok:false},{status:404});};const a=adapter(fetchImpl);await expect(a.verifyConfiguration()).resolves.toMatchObject({webhookSigningSecretSha256:secretHash});await expect(a.readSourceGreenState()).resolves.toMatchObject({observedTargetOrigin:c.targetOrigin});await expect(a.readMonitorHeartbeat()).resolves.toMatchObject({heartbeatAt:now});});
 it('requires an exact checkpoint record for the current release',async()=>{let writes=0;const fetchImpl:typeof fetch=async(url,init)=>{const path=new URL(String(url)).pathname,method=init?.method??'GET';if(path==='/ops/monitor/config')return Response.json(config());if(path==='/ops/monitor/state')return Response.json(state());if(path==='/ops/monitor/backup-checkpoint'&&method==='POST'){writes++;return new Response(null,{status:204});}if(path==='/ops/monitor/backup-checkpoint')return Response.json({schemaVersion:1,environment:c.environmentAlias,release:c.candidateSha,backupRelease:c.candidateSha,...cp,integrityFailureEvidenceSha256:null,configSha256:'f'.repeat(64)});return Response.json({ok:false},{status:404});};const op=adapter(fetchImpl,{...c,configSha256:'f'.repeat(64)}).backupCheckpointOperation(cp);await op.inspect();await op.mutate();expect(writes).toBe(1);await expect(op.readback()).resolves.toMatchObject({status:'verified'});});
 it('rejects a checkpoint retained from a different release',async()=>{const fetchImpl:typeof fetch=async(url,init)=>{const path=new URL(String(url)).pathname,method=init?.method??'GET';if(path==='/ops/monitor/config')return Response.json(config());if(path==='/ops/monitor/state')return Response.json(state());if(path==='/ops/monitor/backup-checkpoint'&&method==='POST')return new Response(null,{status:204});if(path==='/ops/monitor/backup-checkpoint')return Response.json({schemaVersion:1,environment:c.environmentAlias,release:c.candidateSha,backupRelease:'b'.repeat(40),...cp,integrityFailureEvidenceSha256:null,configSha256:'f'.repeat(64)});return Response.json({ok:false},{status:404});};const op=adapter(fetchImpl,{...c,configSha256:'f'.repeat(64)}).backupCheckpointOperation(cp);await op.inspect();await op.mutate();await expect(op.readback()).rejects.toThrow('MONITOR_BACKUP_CHECKPOINT_READBACK_MISMATCH');});
 it('allows an exact target detach readback without falsely requiring a resumed source probe',async()=>{const targetOrigin='https://issue29-restore.example.workers.dev',target={...c,targetRole:'target' as const,targetProbeOrigin:targetOrigin,targetCycleId:'56565656-5656-4565-8565-565656565656'};const fetchImpl:typeof fetch=async(url,init)=>{const path=new URL(String(url)).pathname;if(path==='/ops/monitor/config')return Response.json(config());if(path==='/ops/monitor/maintenance/target'){expect(init?.method).toBe('DELETE');return new Response(null,{status:204});}if(path==='/ops/monitor/state')return Response.json(state(target,{observedTargetOrigin:targetOrigin,maintenance:{active:true,endsAt:'2026-09-08T13:00:00.000Z',incidentId:target.targetCycleId,target:null}}));return Response.json({ok:false},{status:404});};const op=adapter(fetchImpl,target).maintenanceOperation({action:'remove-target',incidentId:target.targetCycleId});await op.inspect();await op.mutate();await expect(op.readback()).resolves.toMatchObject({status:'verified',action:'remove-target'});});
 it('rejects a foreign static target before accepting Worker configuration evidence',async()=>{const fetchImpl:typeof fetch=async()=>Response.json(config());await expect(adapter(fetchImpl,{...c,targetOrigin:'https://foreign.example.workers.dev'}).verifyConfiguration()).rejects.toThrow('MONITOR_CONFIG_IDENTITY_MISMATCH');});
 it('adopts a release only with its dedicated capability and exact post-mutation readback',async()=>{const previousRelease='a'.repeat(40),release='b'.repeat(40),adoption={...c,candidateSha:release,configSha256:'f'.repeat(64),releaseAdoptionToken:'r'.repeat(43)};let current=previousRelease,writes=0;const fetchImpl:typeof fetch=async(url,init)=>{const path=new URL(String(url)).pathname;if(path==='/ops/monitor/config')return Response.json(config(adoption));if(path==='/ops/monitor/state')return Response.json(state(adoption,{release:current}));if(path==='/ops/monitor/release-update'){writes++;expect(init?.headers).toMatchObject({Authorization:`Bearer ${adoption.releaseAdoptionToken}`});expect(JSON.parse(String(init?.body))).toMatchObject({environment:'development',previousRelease,release});current=release;return Response.json({schemaVersion:1,candidateSha:release,previousCandidateSha:previousRelease,previousConfigSha256:'c'.repeat(64)});}return Response.json({ok:false},{status:404});};const op=adapter(fetchImpl,adoption).releaseAdoptionOperation({environment:'development',previousRelease,release,previousConfigSha256:'c'.repeat(64),protectedMergeEvidenceSha256:'d'.repeat(64)});await op.inspect();await op.mutate();expect(writes).toBe(1);await expect(op.readback()).resolves.toMatchObject({status:'verified',candidateSha:release});});
 it('does not retry an ambiguous release-adoption mutation',async()=>{let writes=0;const adoption={...c,candidateSha:'b'.repeat(40),releaseAdoptionToken:'r'.repeat(43)};const fetchImpl:typeof fetch=async url=>{const path=new URL(String(url)).pathname;if(path==='/ops/monitor/state')return Response.json(state(adoption,{release:'a'.repeat(40)}));if(path==='/ops/monitor/release-update'){writes++;return new Response(null,{status:503});}return Response.json({ok:false},{status:404});};const op=adapter(fetchImpl,adoption).releaseAdoptionOperation({environment:'development',previousRelease:'a'.repeat(40),release:'b'.repeat(40),previousConfigSha256:'c'.repeat(64),protectedMergeEvidenceSha256:'d'.repeat(64)});await op.inspect();await expect(op.mutate()).rejects.toThrow('MONITOR_RELEASE_MUTATION_UNCERTAIN_READBACK_ONLY');expect(writes).toBe(1);});
});
